### ISSUE TITLE
PTR skips events when loading the event feed

### ISSUE THREAD

**Issue by olofenglund96** [fsek/app#215]
When using pull to requests, the app skips some events which leaves gaps in the event feed. I'll illustrate with some screenshots:

### Before using PTR
![Screenshot_20190830-165809_F-sektionen](https://user-images.githubusercontent.com/6953059/64030941-cd5c3700-cb47-11e9-8488-ffeebf784e72.jpg)

### After using PTR once
![Screenshot_20190830-165818_F-sektionen](https://user-images.githubusercontent.com/6953059/64030979-e238ca80-cb47-11e9-9efd-6216c9d17751.jpg)

### After using PTR twice
![Screenshot_20190830-165826_F-sektionen](https://user-images.githubusercontent.com/6953059/64031002-eebd2300-cb47-11e9-9e0d-846525012649.jpg)

As one can see, the app skips fetching between 3-9 sep and then skips more events each refresh.

**Comment by davidkrantz** [comment]
Have you tried if [this](https://github.com/fsek/app/pull/186) PR fixes the problem?

**Comment by olofenglund96** [comment]
@davidkrantz unfortunately no!
