### ISSUE TITLE
Custom food preferences is not saved to user 

### ISSUE THREAD

**Issue by davidkrantz** [fsek/app#216]
If a user updates its custom food preferences in the app, it is not properly saved to the user.

**Comment by Edde333** [comment]
The notification settings on the same page has the same problem. If settings are saved and the app reboots, they are not saved.

**Comment by davidkrantz** [comment]
> The notification settings on the same page has the same problem. If settings are saved and the app reboots, they are not saved.

Great job for finding this bug. I can only recreate this for the notification connected to the opening of a signup. I think I have found the problem, and it is due to a bug in `web`.
