### ISSUE TITLE
Make contact page button in introduction tab more visible

### ISSUE THREAD

**Issue by davidkrantz** [fsek/app#241]
Make the button stick out more from the rest, perhaps using a different icon on the button or by changing its color. Below you can find the relevant Photoshop files:
* [Buttons](https://github.com/fsek/app/files/4914043/buttons.zip)
* [Backgrounds](https://github.com/fsek/app/files/4936863/nollning_background.psd.zip)

**Comment by KingJohanna** [comment]
Updated icon images can be found [here](https://drive.google.com/drive/folders/13qLif9eUEpcnDFt_oqhkPf7tKtwN3RDj?usp=sharing) (in progress).
