### ISSUE TITLE
Group information on event signup

### ISSUE THREAD

**Issue by davidwessman** [fsek/app#62]
![img_5724](https://user-images.githubusercontent.com/6763624/29561177-c99e2938-8734-11e7-8c40-7ff6e48c0bf0.PNG)

**Comment by FredrikLastow** [comment]
Did you signup with a group?

**Comment by FredrikLastow** [comment]
I've updated the code to now show "ingen grupp vald" instead of the whole group section being hidden when you signup without selecting a group. This needs to be done on the website too though

https://gyazo.com/ab6e6549fa6b60e908638cde542567a0
