### ISSUE TITLE
Entering new page from an event removes the calendar

### ISSUE THREAD

**Issue by tonitajger** [fsek/app#89]
The calendar disappears when going back from the contact form to the tab. 
Here's a GIF for clarification:
![ed74a42c579e33b09d0f3393f92d2934](https://user-images.githubusercontent.com/34679687/38030298-82628284-3298-11e8-9659-e1b42b012c5b.gif)

**Comment by navro** [comment]
@FredrikLastow do you think the v2 router will solve this?

**Comment by FredrikLastow** [comment]
Yes, that's possible. The routing system is much better in v2. It should work in v1 too though because this case is very similar to the songbook page with the songs.

**Comment by FredrikLastow** [comment]
The issue is already live with the same bug for the user page link on food preferences. Only for ios though.

**Comment by tonitajger** [comment]
The bug for the contact form exists for both ios and android.

**Comment by FredrikLastow** [comment]
Yes, but the bug only exists for ios on live

**Comment by FredrikLastow** [comment]
This isn't closed yet. Be patient young padawan
